<h1><?php echo $this->escapeHtml($this->getMessage());?></h1>
<table>
    <?php foreach ($this->getRecord() as $value) :?>
        <tr>
            <td><?php echo $value->getName();?></td>
            <td><?php echo $value->getImagename();?></td>
        </tr>
    <?php endforeach; ?>
</table>

<form name="postdata" action="<?php echo $this->getUrl('simple/simple/save'); ?>" method="POST">
    <table>
        <tr>
            <td>Name:</td>
            <td><input type="text" name="name" style="width: 500px;"></td>
        </tr>
        <tr>
            <td>Imagename:</td>
            <td><input type="text" name="imagename" style="width: 500px;"></td>
        </tr>
        <tr>
            <td colspan="2"><input type="submit" name="submit" value="submit"></td>
        </tr>
    </table>
</form>